# Generated by Django 5.0.1 on 2024-01-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_uploadfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='pdf/'),
        ),
    ]
