# Generated by Django 5.0.1 on 2024-01-25 08:34

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_uploadfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(default=None, max_length=250, null=True, upload_to=myapp.models.user_directory_path),
        ),
    ]
