# Generated by Django 5.0.1 on 2024-01-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_uploadfile_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='filename',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
